name: mvl_app_core
description: "An App Core features for every app"
version: 1.7.2
homepage: https://github.com/ModelViewLabsOrg/mvl_app_core.git

publish_to: none

module:
  androidX: true

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  package_info_plus: ^9.0.0
  path: ^1.9.1
  async: ^2.13.0
  badges: ^3.1.2
  clock: ^1.1.2
  collection: ^1.19.1
  device_info_plus: ^12.1.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0
  equatable: ^2.0.7
  share_plus: ^12.0.0
  talker_flutter: ^5.0.1
  version: ^3.0.2

  firebase_analytics: ^12.0.2
  firebase_remote_config: ^6.0.2
  firebase_crashlytics: ^5.0.2
  firebase_core: ^4.1.1
  firebase_in_app_messaging: ^0.9.0
  firebase_messaging: ^16.0.2

  uuid: ^4.5.1
  url_strategy: ^0.3.0
  sentry_flutter: ^9.7.0
  aptabase_flutter: #^0.4.1
    git:
      url: https://github.com/GabrielRozendo/aptabase_flutter
      ref: main
  jiffy: ^6.4.3
  url_launcher: ^6.3.2
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.5.3
  overlay_notification: ^23.5.12
  remove_emoji: ^0.0.10
  diacritic: ^0.1.6
  html: ^0.15.6
  in_app_review: ^2.0.11
  font_awesome_flutter: ^10.10.0
  date_field: ^6.0.3
  flutter_riverpod: ^3.0.2
  ulid: ^2.0.1
  nanoid: ^1.0.0
  universal_io: ^2.2.2
  posthog_flutter: ^5.6.0
  supabase_flutter: ^2.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: InterVariable
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf

    - family: MontserratVariable
      fonts:
        - asset: assets/fonts/Montserrat-Variable.ttf
