name: mvl_app_core
description: "An App Core features for every app"
version: 1.1.7
homepage: https://github.com/ModelViewLabsOrg/mvl_app_core.git

publish_to: none

module:
  androidX: true

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  intl: any
  package_info_plus: any
  path: any
  async: any
  badges: any
  clock: any
  collection: any
  device_info_plus: any
  timezone: any
  flutter_timezone: any
  equatable: any
  share_plus: any
  talker_flutter: ^4.7.9
  enum_to_string: any
  version: any

  firebase_analytics: any
  firebase_remote_config: any
  firebase_crashlytics: any
  firebase_core: any
  firebase_in_app_messaging: any
  firebase_messaging: any

  uuid: any
  url_strategy: any
  sentry_flutter: any
  aptabase_flutter: any
    # git:
    #   url: https://github.com/GabrielRozendo/aptabase_flutter
    #   ref: proposal
  jiffy: any
  url_launcher: any
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: any
  overlay_notification: any
  remove_emoji: any
  diacritic: any
  html: any
  in_app_review: any
  font_awesome_flutter: any
  date_field: any
  flutter_riverpod: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: InterVariable
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf

    - family: MontserratVariable
      fonts:
        - asset: assets/fonts/Montserrat-Variable.ttf
