name: mvl_app_core
description: "An App Core features for every app"
version: 2.6.1
homepage: https://github.com/ModelViewLabsOrg/mvl_app_core.git

publish_to: none

module:
  androidX: true

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  mvl_lint: 
    git:
      url: https://github.com/ModelViewLabsOrg/mvl_lint
      ref: main

  intl: ^0.20.3
  package_info_plus: ^10.2.1
  path: ^1.9.1
  async: ^2.13.1
  badges: ^3.2.0
  clock: ^1.1.2
  collection: ^1.19.1
  device_info_plus: ^13.2.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  equatable: ^2.1.0
  share_plus: ^13.3.0
  talker_flutter: ^5.1.20
  version: ^3.0.2

  firebase_analytics: ^12.5.0
  firebase_remote_config: ^6.6.0
  firebase_crashlytics: ^5.3.0
  firebase_core: ^4.14.0
  firebase_in_app_messaging: ^0.9.3
  firebase_messaging: ^16.6.0

  uuid: ^4.6.0
  url_strategy: ^0.3.0
  sentry_flutter: ^9.27.0
  aptabase_flutter: #^0.4.1
    git:
      url: https://github.com/GabrielRozendo/aptabase_flutter
      ref: main
  jiffy: ^6.4.5
  url_launcher: ^6.3.2
  flutter_secure_storage: ^11.0.0
  shared_preferences: ^2.5.5
  overlay_notification: ^23.5.12
  remove_emoji: ^0.0.10
  diacritic: ^0.1.6
  html: ^0.15.6
  in_app_review: ^2.0.12
  # font_awesome_flutter: ^11.0.0
  date_field: ^6.0.3
  ulid: ^2.0.1
  nanoid: ^1.0.0
  universal_io: ^2.3.1
  posthog_flutter: ^5.37.1
  supabase_flutter: ^2.17.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: InterVariable
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf

    - family: MontserratVariable
      fonts:
        - asset: assets/fonts/Montserrat-Variable.ttf
